name: iam-system
services:
  #client_app:
  #  image: client-app/frontend
  #  build: ./client_app
  #  ports:
  #    - "3000:80"
  #  depends_on:
  #    - user_mgmt
  #    - login
  auth_server:
    image: auth_server
    build: ./auth_server
    ports:
      - "8000:8000"
    env_file:
      ./auth_server/.env
    depends_on:
      - auth_db
  api_server:
    image: api_server
    build: ./api_server
    ports:
      - "9000:8000"
    env_file:
      ./api_server/.env
    depends_on:
      - api_db
  auth_db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
  #  volumes:
  #    - ./auth_db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=auth_db
  api_db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
  #  volumes:
   #   - ./api_db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=api_db