name: iam-system
services:
  #client_app:
  #  image: client-app/frontend
  #  build: ./client_app
  #  ports:
  #    - "3000:80"
  #  depends_on:
  #    - user_mgmt
  #    - login
  user_mgmt:
    image: user_mgmt
    build: ./user_mgmt
    ports:
      - "6000:5000"
    depends_on:
      - postgres
  login:
    image: login
    build: ./login
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=auth_db