# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AssignUserRoleBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: str=None, role_id: str=None):  # noqa: E501
        """AssignUserRoleBody - a model defined in Swagger

        :param user_id: The user_id of this AssignUserRoleBody.  # noqa: E501
        :type user_id: str
        :param role_id: The role_id of this AssignUserRoleBody.  # noqa: E501
        :type role_id: str
        """
        self.swagger_types = {'user_id': str, 'role_id': str}

        self.attribute_map = {'user_id': 'userId', 'role_id': 'roleId'}
        self._user_id = user_id
        self._role_id = role_id

    @classmethod
    def from_dict(cls, dikt) -> 'AssignUserRoleBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssignUserRoleBody of this AssignUserRoleBody.  # noqa: E501
        :rtype: AssignUserRoleBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this AssignUserRoleBody.


        :return: The user_id of this AssignUserRoleBody.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this AssignUserRoleBody.


        :param user_id: The user_id of this AssignUserRoleBody.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def role_id(self) -> str:
        """Gets the role_id of this AssignUserRoleBody.


        :return: The role_id of this AssignUserRoleBody.
        :rtype: str
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id: str):
        """Sets the role_id of this AssignUserRoleBody.


        :param role_id: The role_id of this AssignUserRoleBody.
        :type role_id: str
        """

        self._role_id = role_id
