# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdateUserBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self,
                 first_name: str=None,
                 last_name: str=None,
                 email: str=None):  # noqa: E501
        """UpdateUserBody - a model defined in Swagger

        :param first_name: The first_name of this UpdateUserBody.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this UpdateUserBody.  # noqa: E501
        :type last_name: str
        :param email: The email of this UpdateUserBody.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'first_name': str,
            'last_name': str,
            'email': str
        }

        self.attribute_map = {
            'first_name': 'firstName',
            'last_name': 'lastName',
            'email': 'email'
        }
        self._first_name = first_name
        self._last_name = last_name
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateUserBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateUserBody of this UpdateUserBody.  # noqa: E501
        :rtype: UpdateUserBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self) -> str:
        """Gets the first_name of this UpdateUserBody.


        :return: The first_name of this UpdateUserBody.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this UpdateUserBody.


        :param first_name: The first_name of this UpdateUserBody.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this UpdateUserBody.


        :return: The last_name of this UpdateUserBody.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this UpdateUserBody.


        :param last_name: The last_name of this UpdateUserBody.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def email(self) -> str:
        """Gets the email of this UpdateUserBody.


        :return: The email of this UpdateUserBody.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UpdateUserBody.


        :param email: The email of this UpdateUserBody.
        :type email: str
        """

        self._email = email
