# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserRole(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, user_id: str=None, role: str=None):  # noqa: E501
        """UserRole - a model defined in Swagger

        :param id: The id of this UserRole.  # noqa: E501
        :type id: str
        :param user_id: The user_id of this UserRole.  # noqa: E501
        :type user_id: str
        :param role: The role of this UserRole.  # noqa: E501
        :type role: str
        """
        self.swagger_types = {
            'id': str,
            'user_id': str,
            'role': str
        }

        self.attribute_map = {
            'id': 'id',
            'user_id': 'userId',
            'role': 'role'
        }
        self._id = id
        self._user_id = user_id
        self._role = role

    @classmethod
    def from_dict(cls, dikt) -> 'UserRole':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserRole of this UserRole.  # noqa: E501
        :rtype: UserRole
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this UserRole.


        :return: The id of this UserRole.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this UserRole.


        :param id: The id of this UserRole.
        :type id: str
        """

        self._id = id

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserRole.


        :return: The user_id of this UserRole.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserRole.


        :param user_id: The user_id of this UserRole.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def role(self) -> str:
        """Gets the role of this UserRole.


        :return: The role of this UserRole.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this UserRole.


        :param role: The role of this UserRole.
        :type role: str
        """

        self._role = role
