# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TokenResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self,
                 access_token: str=None,
                 refresh_token: str=None,
                 token_type: str=None):  # noqa: E501
        """TokenResponse - a model defined in Swagger

        :param access_token: The access_token of this TokenResponse.  # noqa: E501
        :type access_token: str
        :param refresh_token: The refresh_token of this TokenResponse.  # noqa: E501
        :type refresh_token: str
        :param token_type: The token_type of this TokenResponse.  # noqa: E501
        :type token_type: str
        """
        self.swagger_types = {
            'access_token': str,
            'refresh_token': str,
            'token_type': str
        }

        self.attribute_map = {
            'access_token': 'access_token',
            'refresh_token': 'refresh_token',
            'token_type': 'token_type'
        }
        self._access_token = access_token
        self._refresh_token = refresh_token
        self._token_type = token_type

    @classmethod
    def from_dict(cls, dikt) -> 'TokenResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TokenResponse of this TokenResponse.  # noqa: E501
        :rtype: TokenResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this TokenResponse.


        :return: The access_token of this TokenResponse.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this TokenResponse.


        :param access_token: The access_token of this TokenResponse.
        :type access_token: str
        """

        self._access_token = access_token

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this TokenResponse.


        :return: The refresh_token of this TokenResponse.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this TokenResponse.


        :param refresh_token: The refresh_token of this TokenResponse.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token

    @property
    def token_type(self) -> str:
        """Gets the token_type of this TokenResponse.


        :return: The token_type of this TokenResponse.
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type: str):
        """Sets the token_type of this TokenResponse.


        :param token_type: The token_type of this TokenResponse.
        :type token_type: str
        """

        self._token_type = token_type
